# Generated by Django 3.0.5 on 2022-01-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOne_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='OneToOne_App.Student'),
        ),
    ]
